# Generated by Django 3.1.3 on 2020-11-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_remove_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
