# Generated by Django 3.1.3 on 2020-11-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivingimage',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='drivingimage',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
