# Generated by Django 3.1.3 on 2020-12-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20201124_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyscore',
            name='reason',
            field=models.IntegerField(default=0),
        ),
    ]
