# Generated by Django 3.1.3 on 2020-12-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_safetyscore_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyscore',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
