# Generated by Django 3.1.3 on 2020-11-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_auto_20201121_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsample',
            name='drive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.drive'),
        ),
    ]
