# Generated by Django 3.1.3 on 2020-11-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_auto_20201123_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsample',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='locationsample',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
