# Generated by Django 3.1.3 on 2020-11-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_auto_20201123_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='discounted_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drive',
            name='driving_charge',
            field=models.IntegerField(default=0),
        ),
    ]
